dist: trusty
language: java
jdk:
  - oraclejdk8
  dist: trusty
env:
  - JUMBUNE_HOME=/home/travis/
install: 
  - mvn clean install -DskipTests=true -P yarn

notifications:
  email:
    recipients:
      - dev@collaborate.jumbune.org
    on_success: change # default: change
    on_failure: change # default: change
