package org.jumbune.execution.beans;

public enum DataQualityTaskEnum {
	
	DATA_VALIDATION,DATA_PROFILING,DATA_QUALITY_TIMELINE,XML_DATA_VALIDATION, JSON_DATA_VALIDATION,DATA_SOURCE_COMPARISON,DATA_CLEANSING;
	
}
