package org.jumbune.common.beans;

public enum ApplicationType {

	READ_INTENSIVE, WRITE_INTENSIVE, EXECUTION_INTENSIVE, VARYING_SIZED_FILE_READ_INTENSIVE, MIX_WRITE_EXECUTION_INTENSIVE, READ_WRITE_INTENSIVE, SMALL_FILES_READ_INTENSIVE, CANT_BE_CLASSIFIED_IN_ABOVE;

}
