package org.jumbune.common.yaml.config;

public class YamlFile {
	static String lineSeparator = System.getProperty("line.separator");
	public static StringBuilder str = new StringBuilder().append("hadoopHome: /navinhadoop-0.20.2/").append(lineSeparator)
			.append("sJumbuneHome: /tmp/jHome/").append(lineSeparator).append("master: ").append(lineSeparator).append("  user: <user.name>")
			.append(lineSeparator).append("  host: 192.168.49.71").append(lineSeparator).append("  rsaFile: <user.home>/.ssh/id_rsa")
			.append(lineSeparator).append("  dsaFile: <user.home>/.ssh/id_dsa").append(lineSeparator).append("slaves: ").append(lineSeparator)
			.append("  - user: <user.name> ").append(lineSeparator).append("    hosts: [192.168.49.71]").append(lineSeparator)
			.append("enableDataValidation: FALSE").append(lineSeparator)
			.append("hadoopJobProfile: TRUE").append(lineSeparator).append("profilingParams:")
			.append(lineSeparator).append("  cpu: samples ").append(lineSeparator).append("  heap: sites ").append(lineSeparator)
			.append("  mapers: 0-5").append(lineSeparator).append("  reducers: 0-5").append(lineSeparator).append("  masterJmxPort: 5677")
			.append(lineSeparator).append("  dataNodeJmxPort: 5679").append(lineSeparator).append("  taskTrackerJmxPort: 5678").append(lineSeparator)
			.append("  statsInterval: 15000").append(lineSeparator).append("jobs:").append(lineSeparator).append("  - name: job1")
			.append(lineSeparator).append("    jobClass: org.jumbune.neustar.portps.PortPSJobExecutor").append(lineSeparator)
			.append("    parameters: '2010-05-01, 2010-05-31, 6214'").append(lineSeparator).append("inputFile: /Desktop/PortPSChain-11Apr2012.jar")
			.append(lineSeparator).append("doNotInstrument: ").append(lineSeparator).append(" packages:    ").append(lineSeparator)
			.append(" classes: ").append(lineSeparator).append(" includeAnyways: ").append(lineSeparator).append("debuggerConf: ")
			.append(lineSeparator).append("  maxIfBlockNestingLevel: 4").append(lineSeparator).append("  logLevel:").append(lineSeparator)
			.append("    ifblock: TRUE").append(lineSeparator).append("    switchcase: TRUE").append(lineSeparator)
			.append("    instrumentRegex: FALSE ").append(lineSeparator).append("    instrumentUserDefValidate: FALSE ").append(lineSeparator)
			.append("    partitioner:").append(lineSeparator).append("partitionerSampleInterval: 50").append(lineSeparator)
			.append("mapperSuperClasses:").append(lineSeparator).append("reducerSuperClasses: ").append(lineSeparator).append("regexValidations:")
			.append(lineSeparator).append("  - classname: ").append(lineSeparator).append("    key: ").append(lineSeparator).append("    value: ")
			.append(lineSeparator).append("userValidations:").append(lineSeparator).append("  - classname: ").append(lineSeparator)
			.append("    key: ").append(lineSeparator).append("    value:").append(lineSeparator).append("classpath:").append(lineSeparator)
			.append("  userSupplied:").append(lineSeparator).append("    source: -1").append(lineSeparator).append("    folders: ")
			.append(lineSeparator).append("      - raja").append(lineSeparator).append("    files: ").append(lineSeparator).append("    excludes:")
			.append(lineSeparator).append("      - value").append(lineSeparator).append("  jumbuneSupplied:").append(lineSeparator)
			.append("    source: -1").append(lineSeparator).append("    folders: ").append(lineSeparator)
			.append("      - <user.home>/Desktop/HTF-Alpha/lib/").append(lineSeparator).append("    files: ").append(lineSeparator)
			.append("      - <user.home>/Desktop/HTF-Alpha/resources/UserProperties.yaml").append(lineSeparator).append("    excludes: ")
			.append(lineSeparator).append("      - <user.home>/Desktop/HTF-Alpha/lib/hadoop-0.20.2-core.jar").append(lineSeparator)
			.append("      - <user.home>/Desktop/HTF-Alpha/lib/jsch-0.1.51.jar").append(lineSeparator)
			.append("      - <user.home>/Desktop/HTF-Alpha/lib/gson-2.0.jar").append(lineSeparator)
			.append("      - <user.home>/Desktop/HTF-Alpha/lib/commons-logging-1.1.1.jar").append(lineSeparator)
			.append("      - <user.home>/Desktop/HTF-Alpha/lib/log4j-1.2.16.jar").append(lineSeparator)
			.append("hdfsInputPath: /WordCount/input/      ").append(lineSeparator).append("dataValidation:    ").append(lineSeparator)
			.append("  recordSeparator: \\n").append(lineSeparator).append("  fieldSeparator: \\t").append(lineSeparator).append("  numOfFields: 4")
			.append(lineSeparator).append("  fieldValidationList:").append(lineSeparator).append("    - { ").append(lineSeparator)
			.append("        dataType: int_type, ").append(lineSeparator).append("        fieldNumber: 0,").append(lineSeparator)
			.append("        nullCheck: notNull,").append(lineSeparator).append("        regex: '12*'").append(lineSeparator).append("      } ")
			.append(lineSeparator).append("    - { ").append(lineSeparator).append("        dataType: int_type,").append(lineSeparator)
			.append("        fieldNumber: 1, ").append(lineSeparator).append("        nullCheck: notNull,").append(lineSeparator)
			.append("        regex: '12*'").append(lineSeparator).append("      }").append(lineSeparator).append("    - { ").append(lineSeparator)
			.append("        dataType: int_type, ").append(lineSeparator).append("        fieldNumber: 2, ").append(lineSeparator)
			.append("        nullCheck: mustBeNull,").append(lineSeparator).append("        regex: ' '").append(lineSeparator).append("      }")
			.append(lineSeparator).append("    - { ").append(lineSeparator).append("        dataType: float_type, ").append(lineSeparator)
			.append("        fieldNumber: 3, ").append(lineSeparator).append("        nullCheck: notNull,").append(lineSeparator)
			.append("        regex: '12*'").append(lineSeparator).append("      }");

}
